language: go

go:
  - 1.9.x
  - master

sudo: false

notifications:
  email:
    on_success: never
    on_failure: change

before_install:
  # Download and install dep
  - curl -sI https://github.com/golang/dep/releases/latest | grep -Fi Location  | tr -d '\r' | sed "s/tag/download/g" | awk -F " " '{ print $2 "/dep-linux-amd64"}' | wget --output-document=$GOPATH/bin/dep -i -
  - chmod +x $GOPATH/bin/dep
  # Install linters and misspell
  - go get -u github.com/alecthomas/gometalinter
  - gometalinter --install
  - go get -u github.com/client9/misspell/cmd/misspell

install:
  - make dependencies

deploy:
  - provider: releases
    api_key: ${GITHUB_TOKEN}
    file: dist/prm*
    skip_cleanup: true
    overwrite: true
    file_glob: true
    on:
      tags: true
