language: go

go: master

sudo: false

notifications:
  email:
    on_success: never
    on_failure: change

before_install: go get -u github.com/golang/dep/cmd/dep

install: make dependencies

deploy:
  - provider: releases
    api_key: ${GITHUB_TOKEN}
    file: dist/prm*
    skip_cleanup: true
    file_glob: true
    on:
      tags: true
